### ISSUE TITLE
ORF Finding

### ISSUE THREAD

**Issue by sklages** [FenyoLab/llama-magic#2]
Hi,
I have a question concerning the method how to find ORFs in `dnatoprot_longest_nr.pl`.

There you are looking for the longest stretch from the very beginning of the DNA sequence up to the first stop triplet (stop codon).
This sequence is then stored as longest ORF sequence for subsequent analysis.
But this is not necessarily the longest ORF, sometimes not even an ORF because of `Met` being absent.

Later in `map_peptides_to_proteins.pl` these AA sequences are filtered to match certain criteria, e.g. length. In this step you do take into account the start codon. Why don't you look for the longest `Met` - `*` sequence during translation in  `dnatoprot_longest_nr.pl`? 

I manually checked a few translations of my input sequences and saw that the AA sequences created by `dnatoprot_longest_nr.pl` do not correspond to the "real" (better) ORF (`M->*`).
You probably make some assumptions to do so?

And I probably did miss something ...  :confused:

best,
Sven

**Comment by snkeegan** [comment]
I will take a look at this issue.  I do have an updated script, that uses the known sequence corresponding to the primer regions to decide on the correct reading frame.  This should be more accurate.  It is part of a Llama Magic 2.0 that will be coming out, but not for a few more months.  In the mean time, I can provide this source code to you, if you would like.

Sarah

**Comment by sklages** [comment]
Thank for your kind offer; yes, I would appreciate it if you could provide me with the updated script.
You can email me at klages@molgen.mpg.de

best,
Sven
